### ISSUE TITLE
Session lost after redirect with rack 2.2.3

### ISSUE THREAD

**Issue by onli** [sinatra/sinatra#1742] opened 2022-01-30 16:31 UTC
When using sinatra (2.1.0) with rack 2.2.3, sessions can get lost after redirects to other sites. There also seems to be a browser component to it, but I'm not sure how.

This happens: I run with pipes.digital a small site. As reported by a user at https://github.com/pipes-digital/pipes/issues/84, the login stopped working. The login works with the portier gem (which is maintained by me), that sets a nonce and redirects to a broker, which then redirects back to the sinatra app. After the redirect (always with Firefox, potentially sometimes with other browsers) the session id gets changed and the nonce is lost, making a login impossible. In my log this looks like this:

```
127.0.0.1 - - [30/Jan/2022:17:04:58 +0100] "GET /favicon-16x16.png HTTP/1.1" 200 4521 0.0011
not authorized
get plan: undefined method `[]' for nil:NilClass
{"session_id"=>"ca8ab14432e537d88160c22a91ea940720d6f44404bd53816242e5a661687651", "tracking"=>{"HTTP_USER_AGENT"=>"9c583c86e69f8a08...eaf5b896"}, "redirect_url"=>"http://localhost:9292/", "nonce"=>"0otCxkp17HndmtBfqi2ieg=="}
127.0.0.1 - - [30/Jan/2022:17:05:04 +0100] "GET /mainlogin HTTP/1.1" 200 2955 0.0046
{"session_id"=>"f64a6005ac71f92cf246410f0848e5267322ea1d4de38d0c59b6ba82cfe964f2", "tracking"=>{"HTTP_USER_AGENT"=>"9c583c86e69f8a08...eaf5b896"}}
127.0.0.1 - - [30/Jan/2022:17:05:09 +0100] "POST /_browserid_assert HTTP/1.1" 403 - 0.1288
```
See how the nonce is suddenly gone.

I seem to have fixed it by downgrading rack to 2.2.2 and enabling sessions like this:

```
set :protection, except: [:http_origin, :remote_token] 

configure do
    enable :sessions
    set :session_secret, ENV.fetch('SESSION_SECRET') { SecureRandom.hex(64) }
    set :session_store, Rack::Session::Pool
    ...
end 
```

I'm aware that this might be a bug in rack. However, https://github.com/rack/rack/issues/1682 seems to be the same issue, but points the finger to client libs, which I assume goes also for sinatra (honestly, no idea).

**Comment by dentarg** [comment] 2022-01-30 17:37
> This happens: I run with pipes.digital a small site. As reported by a user at [pipes-digital/pipes#84](https://github.com/pipes-digital/pipes/issues/84)

How different are the code running in production and what's in that repo? I noticed https://github.com/pipes-digital/pipes/issues/79

I think a complete reproduction would be good to have. Looks like the conclusion in https://github.com/rack/rack/issues/1682 was the cookie name, is that a possibility in your case?

**Comment by dentarg** [comment] 2022-01-30 18:08
Is something like this happening? https://developer.mozilla.org/en-US/docs/Web/Privacy/Redirect_tracking_protection

**Comment by onli** [comment] 2022-01-30 18:52
> Looks like the conclusion in rack/rack#1682 was the cookie name, is that a possibility in your case?

How can I check that? I'm not setting a specific name anywhere I'm aware of. The only name I see in the dev tools is `rack.session`.

> How different are the code running in production and what's in that repo? I noticed pipes-digital/pipes#79

It diverged considerable, again with Ruby 3. Made the fork the wrong way. But I'm doing nothing else with the cookies than the code presented here, the web part of the app is pretty vanilla sinatra. If it would help a lot with this issue I can try to force myself to finally take care of it.

> Is something like this happening? https://developer.mozilla.org/en-US/docs/Web/Privacy/Redirect_tracking_protection

Honestly, the browser being responsible was my second guess, after rack-protection. But it does not match with the rack downgrade helping. Plus there is no tracking, and `The origin is classified as a tracker in our Tracking Protection list.` does not apply. The 3 minute delay for `idle-daily` also rules it out imho, the log shows that the broker took only 10 seconds to get back to the sinatra app. Some other protection mechanism maybe?

**Comment by dentarg** [comment] 2022-02-08 10:03
As I wrote in https://github.com/pipes-digital/pipes/issues/84, I think we should close this issue because it doesn't seem to be an issue with Sinatra. I think it is both app and browser specific.

**Closed** 2022-02-08 17:30 UTC

**Comment by onli** [comment] 2022-02-08 17:41
Hey, just in case I can change your minds with this. I have a minimal example where the chance of this being a code error is quite small. It's the example app from https://github.com/portier/sinatra-portier/tree/master/example. One change necessary: Set `sinatra-portier` to the gem version before the workaround, `1.5.2`. I also added puma, resulting in this Gemfile:

```
source "https://rubygems.org"
gem 'sinatra'
gem 'sinatra-portier', '1.5.2'
gem 'puma'
```

A `bundle exec puma -e development` now starts a very small sinatra app with only a login form. And indeed it triggers the same bug, in FF the session is lost after the redirect from the broker, the nonce gone, the login fails.
