### ISSUE TITLE
Stacktraces from middleware swallowed with show exceptions

### ISSUE THREAD

**Issue by ahawkins** [sinatra/sinatra#721] opened 2013-05-31 10:55 UTC
If `show_exceptions` is set and error is thrown from middleware, the stack trace is swallowed. I'm fairly sure this because of this here: https://github.com/sinatra/sinatra/blob/master/lib/sinatra/showexceptions.rb#L11

Here's an example:

```
# config.ru
class ErrorTest
  def initialize(app)
  end

  def call(env)
    raise "test!"
  end
end

class Server < Sinatra::Application
   use ErrorTest
end

run Server
```

Rackup the file. Sinatra will server the 500 page but the trace is missing from the log. I'm not sure if this is a bug or not. It's a weird behavior. If the error is raised inside the sinatra app itself, the stack will appear in the log.

**Comment by zzak** [comment] 2015-02-13 16:39
Marking this ticket for feedback, if no one can reproduce this issue in a reasonable amount of time we should close it.

**Comment by kgrz** [comment] 2015-02-14 10:14
http://cl.ly/image/0A0A163x232Y

I've ran the sample code in the first issue comment and ^ that was what showed up in the error page. Backtrace on the console:

```

0 ❯ curl http://127.0.0.1:9292
RuntimeError: test!
        /Users/kashyap/github_clones/snips/sinatra_721/config.ru:8:in `call'
        /Users/kashyap/github_clones/snips/sinatra_721/vendor/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
        /Users/kashyap/github_clones/snips/sinatra_721/vendor/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
        /Users/kashyap/github_clones/snips/sinatra_721/vendor/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
        /Users/kashyap/github_clones/snips/sinatra_721/vendor/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /Users/kashyap/github_clones/snips/sinatra_721/vendor/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /Users/kashyap/github_clones/snips/sinatra_721/vendor/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
        /Users/kashyap/github_clones/snips/sinatra_721/vendor/ruby/2.1.0/gems/rack-1.6.0/lib/rack/logger.rb:15:in `call'
        /Users/kashyap/github_clones/snips/sinatra_721/vendor/ruby/2.1.0/bundler/gems/sinatra-9929353e6c59/lib/sinatra/base.rb:211:in `call'
        /Users/kashyap/github_clones/snips/sinatra_721/vendor/ruby/2.1.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
        /Users/kashyap/github_clones/snips/sinatra_721/vendor/ruby/2.1.0/gems/rack-1.6.0/lib/rack/methodoverride.rb:22:in `call'
        /Users/kashyap/github_clones/snips/sinatra_721/vendor/ruby/2.1.0/bundler/gems/sinatra-9929353e6c59/lib/sinatra/show_exceptions.rb:21:in `call'
        /Users/kashyap/github_clones/snips/sinatra_721/vendor/ruby/2.1.0/bundler/gems/sinatra-9929353e6c59/lib/sinatra/base.rb:181:in `call'
        /Users/kashyap/github_clones/snips/sinatra_721/vendor/ruby/2.1.0/bundler/gems/sinatra-9929353e6c59/lib/sinatra/base.rb:2021:in `call'
        /Users/kashyap/github_clones/snips/sinatra_721/vendor/ruby/2.1.0/bundler/gems/sinatra-9929353e6c59/lib/sinatra/base.rb:1486:in `block in call'
        /Users/kashyap/github_clones/snips/sinatra_721/vendor/ruby/2.1.0/bundler/gems/sinatra-9929353e6c59/lib/sinatra/base.rb:1795:in `synchronize'
        /Users/kashyap/github_clones/snips/sinatra_721/vendor/ruby/2.1.0/bundler/gems/sinatra-9929353e6c59/lib/sinatra/base.rb:1486:in `call'
        /Users/kashyap/github_clones/snips/sinatra_721/vendor/ruby/2.1.0/gems/rack-1.6.0/lib/rack/tempfile_reaper.rb:15:in `call'
        /Users/kashyap/github_clones/snips/sinatra_721/vendor/ruby/2.1.0/gems/rack-1.6.0/lib/rack/lint.rb:49:in `_call'
        /Users/kashyap/github_clones/snips/sinatra_721/vendor/ruby/2.1.0/gems/rack-1.6.0/lib/rack/lint.rb:37:in `call'
        /Users/kashyap/github_clones/snips/sinatra_721/vendor/ruby/2.1.0/gems/rack-1.6.0/lib/rack/showexceptions.rb:24:in `call'
        /Users/kashyap/github_clones/snips/sinatra_721/vendor/ruby/2.1.0/gems/rack-1.6.0/lib/rack/commonlogger.rb:33:in `call'
        /Users/kashyap/github_clones/snips/sinatra_721/vendor/ruby/2.1.0/bundler/gems/sinatra-9929353e6c59/lib/sinatra/base.rb:218:in `call'
        /Users/kashyap/github_clones/snips/sinatra_721/vendor/ruby/2.1.0/gems/rack-1.6.0/lib/rack/chunked.rb:54:in `call'
        /Users/kashyap/github_clones/snips/sinatra_721/vendor/ruby/2.1.0/gems/rack-1.6.0/lib/rack/content_length.rb:15:in `call'
        /Users/kashyap/github_clones/snips/sinatra_721/vendor/ruby/2.1.0/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
        /Users/kashyap/.rubies/ruby-2.1.3/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
        /Users/kashyap/.rubies/ruby-2.1.3/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
        /Users/kashyap/.rubies/ruby-2.1.3/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'%
```

**Comment by kgrz** [comment] 2015-02-14 10:15
That was using the master branch code, btw.

**Comment by zzak** [comment] 2015-02-16 21:10
I'd like to resolve this before we do the point release, here's the current patch I'm working on:

```diff
diff --git a/lib/sinatra/show_exceptions.rb b/lib/sinatra/show_exceptions.rb
index d7ff54e..2978cbd 100644
--- a/lib/sinatra/show_exceptions.rb
+++ b/lib/sinatra/show_exceptions.rb
@@ -31,6 +31,8 @@ module Sinatra
       end

       env["rack.errors"] = errors
+      env["rack.errors"].puts(exception_string)
+      env["rack.errors"].flush

       # Post 893a2c50 in rack/rack, the #pretty method above, implemented in
       # Rack::ShowExceptions, returns a String instead of an array.
```

and test:

```diff
diff --git a/test/settings_test.rb b/test/settings_test.rb
index 7ec03c6..fe6b08b 100644
--- a/test/settings_test.rb
+++ b/test/settings_test.rb
@@ -274,6 +274,25 @@ class SettingsTest < Minitest::Test
     end
   end

+  describe 'show_exceptions with middleware' do
+    class MiddlewareErrorTest
+      def initialize(app); end
+      def call(env)
+        raise StandardError
+      end
+    end
+
+    it 'returns full backtrace for middleware' do
+      klass = Sinatra.new(Sinatra::Application)
+      mock_app(klass) { use MiddlewareErrorTest }
+
+      get '/'
+      assert_equal 500, status
+      assert body.include?("StandardError")
+      assert body.include?("<code>show_exceptions</code> setting")
+    end
+  end
+
```

The problem is this will actually raise in the test, and need to find a better way to test this middleware. 

Open to suggestions.

**Comment by vipulnsward** [comment] 2015-02-21 20:06
This behavior is on purpose according to https://github.com/vipulnsward/sinatra/commit/45e79fcf825b665688920d7ed15f12265ae50c8e

Using enable `enable :dump_errors` should send the exceptions to log. If this looks wrong behavior, I think the fix is to revert https://github.com/vipulnsward/sinatra/commit/45e79fcf825b665688920d7ed15f12265ae50c8e instead.

**Comment by vipulnsward** [comment] 2015-02-21 20:13
Here's more context of this segregation- https://github.com/sinatra/sinatra/blob/master/lib/sinatra/base.rb#L1111-L1112

**Comment by vipulnsward** [comment] 2015-03-13 17:51
ping @zzak . What are your thoughts about this? 
Anything I can help with to get this closed?

**Comment by zzak** [comment] 2015-03-14 02:05
@vipulnsward Good find!

Let me see if I can reproduce the expected behavior (now that we know it) using the examples here.
If that is the case, I'm ok to release with the current behavior -- and come back to this for 1.5 or future.

**Comment by vipulnsward** [comment] 2015-03-14 04:39
Awesome. Lets do this!

On Saturday, March 14, 2015, Zachary Scott <notifications@github.com> wrote:

> @vipulnsward <https://github.com/vipulnsward> Good find!
>
> Let me see if I can reproduce the expected behavior (now that we know it)
> using the examples here.
> If that is the case, I'm ok to release with the current behavior -- and
> come back to this for 1.5 or future.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/sinatra/sinatra/issues/721#issuecomment-79695375>.
>


-- 
Vipul A.M.
+91-8149-204995

**Comment by fj** [comment] 2015-05-21 15:55
Is this issue still outstanding in either the Rack 1.6.x or 1.5.x series?

**Comment by zzak** [comment] 2015-05-22 21:04
@fj potentially, are you still able to reproduce it?

**Comment by fj** [comment] 2015-05-22 21:36
@zzak When I use:

```
# foo.ru
require 'sinatra/base'

class ErrorTest
  def initialize(app)
  end

  def call(env)
    raise "test!"
  end
end

class Server < Sinatra::Application
  use ErrorTest
end

run Server
```

and run `rackup foo.ru` with Rack 1.6.1 and Sinatra 1.4.6, and then visit localhost:9292, I get an error in the browser but not in the stack trace:

```
[2015-05-22 17:33:44] INFO  WEBrick 1.3.1
[2015-05-22 17:33:44] INFO  ruby 2.2.2 (2015-04-13) [x86_64-linux]
[2015-05-22 17:33:44] INFO  WEBrick::HTTPServer#start: pid=15922 port=9292
127.0.0.1 - - [22/May/2015:17:33:51 -0400] "GET / HTTP/1.1" 500 89172 0.0224
127.0.0.1 - - [22/May/2015:17:33:51 -0400] "GET /__sinatra__/500.png HTTP/1.1" 500 88768 0.0105
```

so it seems like the error is still there.

**Comment by fj** [comment] 2015-06-06 06:30
@zzak Can you confirm whether the above matches your experience?

**Comment by kgrz** [comment] 2015-06-09 05:56
Agree with @fj. I've updated the code he added and these are my findings: https://gist.github.com/76401485d47d94db33c7

**Comment by fj** [comment] 2015-09-25 05:30
What needs to be done to resolve this at this point?

**Comment by zzak** [comment] 2016-01-31 11:09
This isn't exactly blocking, but would like to resolve any open bugs before we release 2.0.

**Closed** 2016-05-10 08:15 UTC
Labels: bug

**Comment by fj** [comment] 2016-05-10 14:53
Thanks for the fix @zzak :heart:.
