### ISSUE TITLE
Sinatra fails after upgrade

### ISSUE THREAD

**Issue by navtis** [sinatra/sinatra#1194] opened 2016-10-26 15:15 UTC
I have a back-end Sinatra application using Webrick which has been running without problems for some years. I just needed to upgrade the system OS to the new Ubuntu LTS, and Sinatra no longer works for me. I have run 'gem update all' but suspect there is some versioning incompatibility. Here's the error log:

```
[2016-10-26 12:53:33] INFO  WEBrick 1.3.1
[2016-10-26 12:53:33] INFO  ruby 2.3.1 (2016-04-26) [i386-linux-gnu]
== Sinatra (v1.4.7) has taken the stage on 5225 for test with backup from WEBrick
[2016-10-26 12:53:33] INFO  WEBrick::HTTPServer#start: pid=6170 port=5225
[2016-10-26 12:54:06] ERROR NameError: uninitialized constant Rack::Handler::WEBrick::QUERY_STRING
        /var/lib/gems/2.3.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:81:in `service'
        /usr/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
        /usr/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
        /usr/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
81.2.83.123 - - [26/Oct/2016:12:54:06 UTC] "GET / HTTP/1.1" 500 349
- -> /

```

Any ideas?

**Comment by mwpastore** [comment] 2016-11-15 16:55
@navtis You can try to fix your app, but you may run into this issue each time you upgrade Ubuntu. Instead of relying on the operating system Ruby and gems, it might be worthwhile to use something like [rbenv](https://github.com/rbenv/rbenv) and [ruby-build](https://github.com/rbenv/ruby-build), [rvm](http://rvm.io), or [chruby](https://github.com/postmodern/chruby) and [ruby-install](https://github.com/postmodern/ruby-install) with a target Ruby version, and build a Gemfile for your application that lists specific versions of gems are known to be compatible with your Ruby and application. This guarantees that your app will always run with the correct Ruby ecosystem regardless of the operating system.

**Comment by jkowens** [comment] 2016-11-15 20:26
@navtis do you have another version of rack installed on the system besides v1.6.4? It seems like maybe you have v1.5.5 or older that is conflicting.

**Comment by coin8086** [comment] 2016-11-15 23:52
@navtis BTW, Webrick makes sense only in development environment. You may need to turn to a better/stronger Ruby Rack server, say Unicorn. It's not difficult.

**Comment by zzak** [comment] 2016-12-14 10:15
@navtis Sadly, the state of things has changed over the years and the best advice is to follow what @mwpastore has suggested and modernize your app by isolating your dependencies using a tool like [bundler](https://bundler.io).

I'm going to close this issue because it's clearly not a bug on our end.

Feel free to continue the discussion of how to upgrade your app here, or suggest moving to [stackoverflow](https://stackoverflow.com) for more help.

**Closed by zzak** 2016-12-14 10:15 UTC
