### ISSUE TITLE
on mac  "\x89"

### ISSUE THREAD

**Issue by and09** [sinatra/sinatra#1288] opened 2017-04-19 18:26 UTC
# gem install sinatra
Fetching: sinatra-1.4.8.gem (100%)
Successfully installed sinatra-1.4.8
Parsing documentation for sinatra-1.4.8
unable to convert "\x89" from ASCII-8BIT to UTF-8 for lib/sinatra/images/404.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for lib/sinatra/images/500.png, skipping
Installing ri documentation for sinatra-1.4.8

1 gem installed

**Comment by codeblooded** [comment] 2017-06-01 23:55
What version of macOS, Ruby, and RubyGems are you using?  I'm trying to duplicate, but I haven't been able to yet...

- macOS 10.12.5 (16F73) 
- RubyGems 2.6.11
- ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

**Comment by Ox16** [comment] 2017-07-02 06:45
mac OS = 10.12.4 (16E195)
$ gem -v
2.4.8
$ ruby -v
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]

**Comment by zzak** [comment] 2017-07-04 05:56
@and09 @Ox16 Could you try upgrading to the latest version of Ruby and installing the gem?

**Comment by jkowens** [comment] 2018-02-20 04:39
The issue stems from rdoc and the fix is to update the rdoc gem:
```
gem update rdoc
```
This is a duplicate of  https://github.com/sinatra/sinatra/issues/1089.

cc: @namusyaka

**Comment by namusyaka** [comment] 2018-02-20 11:43
Makes sense. Closing, let us know if you still have any issues.
@jkowens Thanks!

**Closed by namusyaka** 2018-02-20 11:43 UTC
Labels: feedback, help wanted
