### ISSUE TITLE
Failure in displaying error page

### ISSUE THREAD

**Issue by zmyrgel** [sinatra/sinatra#977] opened 2015-02-27 09:00 UTC
when my app causes an exception I get an empty page in sinatra.

The log file shows that the sinatra error block is causing error:

```
 E, [2015-02-27T10:56:53.429375 #22053] ERROR -- : app error: no implicit conversion of Symbol into String (TypeError)
E, [2015-02-27T10:56:53.429534 #22053] ERROR -- : /srv/web/lapa/releases/20150226113429/lapa.rb:71:in `+'
E, [2015-02-27T10:56:53.429570 #22053] ERROR -- : /srv/web/lapa/releases/20150226113429/lapa.rb:71:in `block in <top (required)>'
E, [2015-02-27T10:56:53.429596 #22053] ERROR -- : /srv/web/lapa/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
E, [2015-02-27T10:56:53.429620 #22053] ERROR -- : /srv/web/lapa/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
E, [2015-02-27T10:56:53.429644 #22053] ERROR -- : /srv/web/lapa/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `[]'
E, [2015-02-27T10:56:53.429668 #22053] ERROR -- : /srv/web/lapa/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
E, [2015-02-27T10:56:53.429692 #22053] ERROR -- : /srv/web/lapa/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
E, [2015-02-27T10:56:53.429716 #22053] ERROR -- : /srv/web/lapa/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
E, [2015-02-27T10:56:53.429751 #22053] ERROR -- : /srv/web/lapa/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1126:in `block in error_block!'
E, [2015-02-27T10:56:53.429777 #22053] ERROR -- : /srv/web/lapa/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1123:in `reverse_each'
E, [2015-02-27T10:56:53.429807 #22053] ERROR -- : /srv/web/lapa/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1123:in `error_block!'
E, [2015-02-27T10:56:53.429850 #22053] ERROR -- : /srv/web/lapa/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1115:in `handle_exception!'
E, [2015-02-27T10:56:53.429877 #22053] ERROR -- : /srv/web/lapa/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1079:in `block in dispatch!'
E, [2015-02-27T10:56:53.429901 #22053] ERROR -- : /srv/web/lapa/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
E, [2015-02-27T10:56:53.429927 #22053] ERROR -- : /srv/web/lapa/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
E, [2015-02-27T10:56:53.429955 #22053] ERROR -- : /srv/web/lapa/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
E, [2015-02-27T10:56:53.429980 #22053] ERROR -- : /srv/web/lapa/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1079:in `rescue in dispatch!'
E, [2015-02-27T10:56:53.430004 #22053] ERROR -- : /srv/web/lapa/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1086:in `dispatch!'
E, [2015-02-27T10:56:53.430028 #22053] ERROR -- : /srv/web/lapa/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
E, [2015-02-27T10:56:53.430051 #22053] ERROR -- : /srv/web/lapa/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
E, [2015-02-27T10:56:53.430075 #22053] ERROR -- : /srv/web/lapa/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
E, [2015-02-27T10:56:53.430098 #22053] ERROR -- : /srv/web/lapa/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
E, [2015-02-27T10:56:53.430122 #22053] ERROR -- : /srv/web/lapa/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
E, [2015-02-27T10:56:53.430148 #22053] ERROR -- : /srv/web/lapa/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
E, [2015-02-27T10:56:53.430174 #22053] ERROR -- : /srv/web/lapa/shared/bundle/ruby/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
E, [2015-02-27T10:56:53.430204 #22053] ERROR -- : /srv/web/lapa/shared/bundle/ruby/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
E, [2015-02-27T10:56:53.430247 #22053] ERROR -- : /srv/web/lapa/shared/bundle/ruby/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
E, [2015-02-27T10:56:53.430273 #22053] ERROR -- : /srv/web/lapa/shared/bundle/ruby/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
E, [2015-02-27T10:56:53.430297 #22053] ERROR -- : /srv/web/lapa/shared/bundle/ruby/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
...
```

The code block in question is taken from Sinatra documentation:

```ruby
error do
  status 500
  'Sorry there was a nasty error - ' + env['sinatra.error'].name  # <-- line 71 
end
```

**Comment by kytrinyx** [comment] 2015-02-27 14:34
Have you tried building your app against the most recent version of master?

**Comment by ipoval** [comment] 2015-03-18 03:50
Related stack-trace for the latest (1.4.5) version of the gem  - the problem is fixed on master branch https://github.com/sinatra/sinatra/blob/master/lib/sinatra/show_exceptions.rb#L37

```
NoMethodError (undefined method `join' for #<String:0x007fc9e4801208>):
  sinatra (1.4.5) lib/sinatra/show_exceptions.rb:39:in `rescue in call'
  sinatra (1.4.5) lib/sinatra/show_exceptions.rb:21:in `call'
  sinatra (1.4.5) lib/sinatra/base.rb:180:in `call'
  sinatra (1.4.5) lib/sinatra/base.rb:2014:in `call'
```

```
   32:         body = pretty(env, e)
   33:       end
   34: 
   35:       env["rack.errors"] = errors
   36: 
=> 37:       [500,
   38:        {"Content-Type" => content_type,
   39:         "Content-Length" => Rack::Utils.bytesize(body.join).to_s},
   40:        body]
```

**Comment by kytrinyx** [comment] 2015-03-22 20:54
I'm closing this, since it's fixed in master. We expect to be cutting a release soon, but in the mean time you can point your gemfile to the tip of master, or temporarily include Josh Cheek's gem `sinatra_fix_951`

```
gem 'sinatra-fix_951', require: 'sinatra/fix_951'
```

https://github.com/sinatra/sinatra/issues/951#issuecomment-84572703

**Closed by kytrinyx** 2015-03-22 20:54 UTC
