### ISSUE TITLE
Stop to overwrite max-age on Cache-Control header 

### ISSUE THREAD

**Issue by iguchi1124** [sinatra/sinatra#1424] opened 2018-04-27 17:26 UTC
related issue #1404

I think `Expires` header should not have overwritten with `Cache-Control max-age` header in `expires` method.

I checked RFC2616 which is referenced by implementer probably,

https://tools.ietf.org/html/rfc2616#section-14.21

```
Note: if a response includes a Cache-Control field with the max-
age directive (see section 14.9.3), that directive overrides the
Expires field.
```

So, I think forcibly overwriting was not intentional.
For example, Expires http-date and max-age duration are not able to indicates same time by network latency.I think `max-age` will be counting from receiving HTTP-response.

**Comment by jkowens** [comment] 2019-08-22 21:34
Closing because this appears to be a duplicate of #1403.

**Closed by jkowens** 2019-08-22 21:34 UTC
