### ISSUE TITLE
Error Data_mapper with Sinatra 2.0.0

### ISSUE THREAD

**Issue by smanezItec** [sinatra/sinatra#1301] opened 2017-05-29 10:08 UTC
My Gemfile.lock

`source "https://rubygems.org"

gem 'sinatra', '1.4.8'
gem 'data_mapper', '1.2.0'
gem 'dm-sqlite-adapter', '1.2.0'
gem 'json', '~>1.6'
gem 'thin', '1.7.0'
gem 'slim', '3.0.8'
gem 'shotgun', '0.9.2'` 

Gem::ConflictError: Unable to activate dm-serializer-1.2.2, because json-2.1.0 conflicts with json (~> 1.6)

**Comment by zzak** [comment] 2017-06-01 02:18
Closing as duplicate of #1294

**Closed by zzak** 2017-06-01 02:18 UTC
