### ISSUE TITLE
rack 2.0.8 breaking change

### ISSUE THREAD

**Issue by baelter** [sinatra/sinatra#1589] opened 2020-01-09 14:34 UTC
Should `session[:session_id]` be `.public_id` because of https://github.com/rack/rack/issues/1432 perhaps?

**Comment by dentarg** [comment] 2020-01-09 17:50
@baelter is there a problem in Sinatra? do you have a repro?

**Comment by baelter** [comment] 2020-01-10 09:14
Not sure, just noticed that `session[:session_id]` used to be `String` but is `Object` since rack 2.0.8

**Comment by ernestoe** [comment] 2020-01-11 15:08
I had a problem with this. Got an error like this: 'Sidekiq web, NoMethodError at /sidekiq/ undefined method `each' for #<ActionDispatch::Request::Session:0x7fdf43f67d20 not yet loaded>'. Regressed to rack 2.0.8 and all is well again.

**Comment by dentarg** [comment] 2020-01-11 22:01
@baelter can you try with rack 2.1.0 that should fix https://github.com/rack/rack/issues/1432? 

@ernestoe that doesn't sound like a Sinatra problem, I'm afraid

(Still curious to see code that reproduces the problem with Sinatra.)

**Comment by dentarg** [comment] 2020-01-11 22:05
@ernestoe Sounds like you might have run into https://github.com/rack/rack/pull/1428, looks like it will be fixed in a coming rack release

**Comment by ernestoe** [comment] 2020-01-13 18:06
In my case problem has been solved with rack 2.1.1 . Thank for your comments.

**Closed** 2020-03-10 20:46 UTC
