### ISSUE TITLE
respond_with tried to require every engine Tilt knows about

### ISSUE THREAD

**Issue by ericroberts** [sinatra/sinatra#1172] opened 2016-08-18 19:17 UTC
When it does `Tilt[engine]` in template_for, it tries to require the engine, but most of them are not installed.

**Comment by ericroberts** [comment] 2016-08-18 19:18
Downgrading `tilt` to 1.4 makes it work for now.

**Comment by zzak** [comment] 2016-08-19 01:58
@ericroberts Can you provide a reproducible script?

**Comment by markpitchless** [comment] 2016-11-24 03:44
I just came across the same issue, template_for trying to require all engines.

Worked around it by forcing it to only search the engines I'm using:
```ruby
settings.template_engines[:all] = [:erb]
```

Using sinatra and contrib 1.4.7 with tilt 2.0.5. Triggered by:
```ruby
require 'sinatra'
require 'sinatra/respond_with'
get '/' do
  respond_with :index
end
```
```
curl -v -H "Accept: text/html" 'http://localhost:4567/'
```

Looks like this bit of code in `respond_with.rb`:
```ruby
          # not exactly like Tilt[engine], but does not trigger a require
          if Tilt.respond_to?(:mappings)
            klass = Tilt.mappings[Tilt.normalize(engine)].first
          else
            klass = Tilt[engine]
          end
```
The current tilt doesn't seem to have a `mappings` or `normalize` method anymore.

**Comment by zzak** [comment] 2017-01-30 03:23
Could someone with context on this [open an issue on tilt](https://github.com/rtomayko/tilt/issues/new) to see if there is a workaround/alternative?

**Comment by mwpastore** [comment] 2017-01-30 03:31
Go ahead and assign it to me if you'd like, I'll see what I can work out with them.

**Comment by zzak** [comment] 2017-01-30 03:38
@mwpastore :bow:

**Closed** 2019-10-26 21:15 UTC
Labels: feedback, sinatra-contrib
