### ISSUE TITLE
No '+' in URL?

### ISSUE THREAD

**Issue by LorenzLoesch** [sinatra/sinatra#1031] opened 2015-09-08 15:03 UTC
Hi,

Some of my files in my public folder have a '+' in their names. 
When I try to access these files via browser, I get a 404 error. There is no additional log output.

I triple-checked that the files do exist and the URL is correct. I can access other files in the public folder. If I rename the files, so they don't contain a '+' in their name, I can access them as well.

Unfortunately, I can not avoid having '+' characters in my filenames.

Has this been experienced before?

Best Regards,
Lorenz

**Comment by rennex** [comment] 2015-09-08 15:37
It seems that Sinatra's built-in static file server unescapes the URL, which turns "+" signs into spaces. I tested Rack::Static, and it does the same thing. It's rather silly (and probably a bug), since that should only happen in the query string part (after a ?).

You can get around it by encoding the plus signs as %2b in the requests. If you can't do that, you'll have to fix the server side. If you can run a reverse proxy (such as nginx or Apache) in front of your app and have it serve the static files, that would fix the issue and be beneficial in other ways as well.

A final option would be to write a custom Rack middleware that serves static files without touching the + signs (or modify Rack::Static in that regard) and insert it before your main app in config.ru.

**Comment by LorenzLoesch** [comment] 2015-09-08 15:49
rennex, thanks for your reply.

I already tried escaping the plus signs, and that didn't work for me as well (and also wouldn't be a solution for my environment).

I will take a look at your other suggestions.

**Comment by kytrinyx** [comment] 2015-09-08 16:26
URL-encoding a space turns it into a `+`. I would recommend using `CGI::escape` to encode your filename, which will encode the `+` as a `%2b` as suggested by @rennex.

**Comment by kytrinyx** [comment] 2015-09-08 16:26
I just saw your second comment @LorenzLoesch which says that URI escaping your plus sign doesn't work. Could you say more about that?

**Comment by mattwildig** [comment] 2015-09-08 16:42
I think this recent change in Rack is relevant here: rack/rack@978eb9b9935d388ca8cc45fe31c870b9bc0aaab2. It’s only in master currently, but I _think_ the correct behaviour would be for Sinatra to change the current use of [`Rack::Utils.unescape`](https://github.com/sinatra/sinatra/blob/0827bf9eb51562c67aaa5a587cc20e475525a1b5/lib/sinatra/base.rb#L1037) when serving static files for the new `unescape_path`.

**Comment by rennex** [comment] 2015-09-08 19:20
@mattwildig I agree, unescape_path looks exactly like what's needed here.

**Comment by kytrinyx** [comment] 2015-09-08 19:26
Ah, good find, @mattwildig.

**Comment by LorenzLoesch** [comment] 2015-09-09 08:21
@kytrinyx  - on our server, I created 2 testfiles:
https://sdk.v-play.net/filewithout.txt and
https://sdk.v-play.net/filewith++.txt

both files do exist.
http://i.cubeupload.com/P9CyIF.png

Now you can verify that even with an escaped URL, the 404 error occurs:
https://sdk.v-play.net/filewith%2B%2B.txt

Best Regards,
Lorenz

**Comment by kytrinyx** [comment] 2015-09-09 14:56
Thanks for the reproduction steps, @LorenzLoesch.

**Comment by kgrz** [comment] 2015-09-09 15:48
Is [this issue](https://github.com/sinatra/sinatra/issues/1004) related to this?

**Comment by kytrinyx** [comment] 2015-09-09 16:15
@kgrz I think it is. And it even has an open PR. I'll test that today. Thanks!

**Comment by kytrinyx** [comment] 2015-09-10 04:09
I've merged #1018 which should fix this issue.

**Closed by kytrinyx** 2015-09-10 04:09 UTC
Labels: bug
