### ISSUE TITLE
ArgumentError - wrong number of arguments (given 2, expected 0): sinatra-2.1.0/lib/sinatra/base.rb:1553:in `caller_locations'

### ISSUE THREAD

**Issue by vs37559** [sinatra/sinatra#1710] opened 2021-07-12 12:10 UTC
I am facing this issue when I try to include `ActiveSupport::Rescuable` in my Sinatra Application. Any ideas??

> ERROR - 12/Jul/2021 17:31:27 ArgumentError - wrong number of arguments (given 2, expected 0):
>  /Users/usr/.rvm/gems/ruby-2.7.2/gems/sinatra-2.1.0/lib/sinatra/base.rb:1553:in 'caller_locations'
> rake aborted!
> ArgumentError: wrong number of arguments (given 2, expected 0)
> /Users/usr/.rvm/gems/ruby-2.7.2/gems/sinatra-2.1.0/lib/sinatra/base.rb:1553:in 'caller_locations'
> /Users/usr/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.3.2/lib/active_support/core_ext/class/attribute.rb:126:in 'class_attribute'
> /Users/usr/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.3.2/lib/active_support/rescuable.rb:13:in 'block in <module:Rescuable>'
> /Users/usr/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.3.2/lib/active_support/concern.rb:136:in 'class_eval'
> /Users/usr/.rvm/gems/ruby-2.7.2/gems/activesupport-6.1.3.2/lib/active_support/concern.rb:136:in 'append_features'

Sinatra: v2.1.0
Ruby: v2.7.2
Active Support: v6.1.3.2

**Comment by esparta** [comment] 2021-07-13 16:30
can you provide a reproducible script/project? that make easy for maintainers & contributors to understand the issue.

**Comment by dentarg** [comment] 2021-07-13 21:03
active_support tries to call `caller_locations` at https://github.com/rails/rails/blob/v6.1.3.2/activesupport/lib/active_support/core_ext/class/attribute.rb#L126

Looks like there's a mismatch between `caller_locations` in Sinatra, introduced in https://github.com/sinatra/sinatra/commit/9d67449452141aa4f47ffbc1a8fc3e560bb528c0 (2009-04-20)

https://github.com/sinatra/sinatra/blob/0a50b5608d3ff4fda563cc3d3a600d581c57d8e0/lib/sinatra/base.rb#L1552-L1556

and the [`caller_locations`](https://ruby-doc.org/core-2.0.0/Kernel.html#caller_locations-method) method introduced in [Ruby 2.0 (2013-02-24)](https://www.ruby-lang.org/en/news/2013/02/24/ruby-2-0-0-p0-is-released/): http://blog.marc-andre.ca/2013/02/23/ruby-2-by-example/

**Comment by vs37559** [comment] 2021-07-19 07:21
@esparta Steps to reproduce: 

- Initialize a basic sinatra application with above mentioned versions.
- Add `ActiveSupport:Rescuable` to your `app.rb` file.
- Try to initialize the app by starting the server/console.
- The error will pop-up.

@dentarg I also analysed it till this point. Do we have any way to monkeypatch this?

**Comment by jkowens** [comment] 2021-08-17 14:42
See also this PR: https://github.com/sinatra/sinatra/pull/1491

**Comment by jkowens** [comment] 2021-10-06 15:29
Closed by #1491. Look for the fix in a 3.0 release.

**Closed by jkowens** 2021-10-06 15:29 UTC
