### ISSUE TITLE
Process.detach cause sinatra-1.4.7 auto exit

### ISSUE THREAD

**Issue by roroco** [sinatra/sinatra#1168] opened 2016-08-13 15:48 UTC
here is [my stackoverflow question](http://stackoverflow.com/questions/38934398/process-detach-cause-sinatra-1-4-7-auto-exit)

**Comment by rennex** [comment] 2016-08-13 16:48
I answered it on StackOverflow.

But I think this calls for a fix in Sinatra. Why is forking so unsafe by default? Actually, not just unsafe, it's guaranteed destruction.

Also, why does a `quit!` inside a forked child process cause the parent to exit? Shouldn't there be a clean separation between the two processes?

**Comment by zzak** [comment] 2016-12-14 10:37
@rennex I'm not sure anything should change, because we don't want to deal with behavior of `fork` inside Sinatra. This should be up to the user.

Also, I would expect `quit!` to be behave similar to Ruby's `Process.exit!`

**Comment by mwpastore** [comment] 2017-01-03 10:56
Oh, hi, it looks like #1229 is a duplicate of this issue. I provided another solution over there in addition to @rennex's excellent SO answer. tl;dr: use a rackup script.

Just to weigh in on the larger question, I don't think there's any reason to fix this in Sinatra, because the problem isn't really with Sinatra, it's with Ruby. The way a forked process inherits the parent process's `at_exit` handler is causing this problem. And I'm no systems programmer but I believe this goes all the way back to how POSIX `fork(2)` works, so it's not likely to be fixed in Ruby, either!

**Comment by zzak** [comment] 2017-01-30 03:20
Thank you!

**Closed** 2017-01-30 03:19 UTC
Labels: feedback
