### ISSUE TITLE
shouldn't the opening example include `Sinatra::Application.run!` ?

### ISSUE THREAD

**Issue by yoLotus** [sinatra/sinatra#1507] opened 2018-12-17 11:13 UTC
Hello,

I tried to run the opening example as written in the first lines of the README but when running `ruby myapp.rb` it silently exit without listening on port `4567`.

I needed to add `Sinatra::Application.run!` to make it worked:

```ruby
require 'bundler/inline'
gemfile do
  source 'https://rubygems.org'
  gem 'sinatra'
end

get '/' do
  'Hello world!'
end
Sinatra::Application.run!
```

Did I miss something?

**Comment by namusyaka** [comment] 2018-12-21 17:48
@yoLotus Thanks for your report. That is good point.
At first, we haven't expected to use `require 'sinatra'` combined with `require 'bundler/inline'`
Please take a look at: https://github.com/sinatra/sinatra/blob/69956da995b1a4c06b481431129e3e516800a0e2/lib/sinatra/main.rb#L26

In your case, `Application.run?` always returns `false` because of:
https://github.com/sinatra/sinatra/blob/69956da995b1a4c06b481431129e3e516800a0e2/lib/sinatra/main.rb#L11

`app_file ` indicates actual caller which means `bundler/inline.rb` so `run?` always returns `false`. This is root cause.

In order to avoid the issue quickly, you can do it by setting `app_file` manually:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'sinatra', require: 'sinatra'
end

set :app_file, $0

get '/' do
  'Hello world!'
end
```
However, this is not understandable. We need to take care the case.

**Comment by yoLotus** [comment] 2018-12-23 14:43
Hello @namusyaka , thanks for your detailed answer.

I didn't know about the `:app_file` setting. I tried your example and It worked perfectly.

I usually use `bundler/inline` script to test gems or quickly write small scripts with ruby, I don't know if it is a common way to do things but If you think it is relevant to add your example in the documentation, I can handle it in a PR. Where should I add it ?

**Comment by namusyaka** [comment] 2018-12-24 15:05
@yoLotus Thanks for confirmation.
I'd like to make implementation handle the case rather than documentation. I've just marked this as a bug.

**Comment by yoLotus** [comment] 2018-12-25 20:39
Just a side question but I was wondering if it was really necessary to run `application.run?` in the `main.rb` here:

```ruby
at_exit { Application.run! if $!.nil? && Application.run? } 
```

Only check that `$!` is nil shouldn't be enough ?

Otherwise when I modify the `main.rb` like this, it works without to be forced to explicitly set `app_file` in my script:

```ruby
module Sinatra
  class Application < Base
    # we assume that the first file that requires 'sinatra' is the
    # app_file. all other path related options are calculated based
    # on this path by default.
    set :app_file, caller_files.first || $0
    set :expanded_caller_files, caller_files.map{ |f| File.expand_path(f) }
    set :run, Proc.new { expanded_caller_files.include?(File.expand_path($0)) }
    # ...
  end
  at_exit { Application.run! if $!.nil? && Application.run? }
end
```

But I am not sure it's the best way to do...

**Comment by namusyaka** [comment] 2019-02-03 16:11
@yoLotus I have created [a patch](https://github.com/sinatra/sinatra/pull/1520) for fixing the issue. Could you take a look?

**Comment by yoLotus** [comment] 2019-02-04 21:57
Hello @namusyaka 

Just tried your patch by running the example of my first comment of this thread (by removing the `Sinatra::Application.run!` statement) it works perfectly, and the diff is really minimal.

Don't know if a test should be add, but if you think it is not necessary, everything seems good on my side.

Thanks a lot for the patch!

**Comment by namusyaka** [comment] 2019-02-05 16:22
It's worth testing, of course. Thanks for confirming.

**Closed** 2019-02-05 23:19 UTC
Labels: bug
